vscode:
  extensions:
    - astro-build.astro-vscode
tasks:
  - before: |
      # Get latest pnpm version, in case the custom docker image was not updated
      # Until this issue gets resolved - https://github.com/gitpod-io/gitpod/issues/12551
      curl -fsSL https://get.pnpm.io/install.sh | SHELL=`which bash` bash -
    init: |
      nvm install 18.12.1
      pnpm install
      pnpm run build
    command: |
      .gitpod/gitpod-setup.sh
ports:
  - port: 3000
    onOpen: open-preview
